/* Importaciones */
import { useState } from "react"
import { Link } from "react-router-dom"
import ParemiasComp from "../components/Paremias"

const Paremias = () => {
  const [menuDesplegable, setMenuDesplegable] = useState(false)
  const [dichos, setDichos] = useState(true)
  const [refranes, setRefranes] = useState(false)
  const dichosDatos = [
    { urlImagen: "Imagesdichos/cria_fama.webp", expresion: "«Cría fama y échate a dormir»", significado: "Indica que una vez que te has labrado una reputación (buena o mala), esta te precederá y condicionará la opinión de los demás sin que tengas que hacer nada más, ya que es muy difícil cambiar la primera impresión.", origen: "Proviene de la idea de que la fama es una inercia difícil de frenar. Se basa en una fábula donde un perro, tras salvar a un niño y ganar fama de héroe, pudo permitirse descansar mientras todos asumían que seguía siendo el más valiente, aunque ya no hiciera nada." },
    { urlImagen: "Imagesdichos/ojo_amo_caballo.webp", expresion: "«El ojo del amo engorda al caballo»", significado: "Indica que las cosas se cuidan y funcionan mejor cuando es el propio dueño quien las supervisa directamente. La atención personal y el interés del propietario aseguran que el trabajo se haga correctamente.", origen: "Proviene de la sabiduría popular agraria y ganadera. Se basa en la observación de que un cuidador ajeno nunca tendrá el mismo celo que el dueño, quien, al estar presente y atento ('el ojo'), se asegura de que el caballo esté bien alimentado y sano." },
    { urlImagen: "Imagesdichos/buen_entendedor.webp", expresion: "«A buen entendedor pocas palabras bastan»", significado: "Indica que una persona inteligente o atenta comprende rápidamente lo que se quiere decir sin necesidad de explicaciones detalladas. Apela a la perspicacia y a la economía del lenguaje.", origen: "Tiene raíces clásicas en el latín ('Dictum sapienti sat est'). Se popularizó en la literatura del Siglo de Oro, apareciendo en obras como El Quijote, reflejando la idea de que la comunicación es más eficaz cuando hay entendimiento mutuo sin rodeos." },
    { urlImagen: "Imagesdichos/perro_flaco.webp", expresion: "«A perro flaco todo son pulgas»", significado: "Indica que a las personas que ya tienen problemas o atraviesan una mala racha, suelen acumulárseles nuevas desgracias. La adversidad parece atraer más adversidad.", origen: "Proviene de la observación empírica en el campo: los parásitos prefieren a los animales débiles o enfermos porque tienen menos defensas para espantarlos. Es una metáfora de cómo la pobreza o la debilidad atraen infortunios adicionales." },
    { urlImagen: "Imagesdichos/dicho_hecho.webp", expresion: "«Del dicho al hecho hay mucho trecho»", significado: "Advierte que existe una gran diferencia entre lo que se promete y lo que realmente se cumple. Nos recuerda que hablar es fácil, pero llevar las palabras a la acción requiere un esfuerzo que no siempre se realiza.", origen: "Es una expresión de origen medieval muy común en la literatura clásica española. La palabra 'trecho' hace referencia a la distancia física, creando una metáfora sobre el largo camino que separa la intención de la realidad." },
    { urlImagen: "Imagesdichos/san_pedro.webp", expresion: "«A quien Dios se la dé, San pedro se la bendiga»", significado: "Se usa para expresar conformidad o resignación ante la suerte o el éxito de alguien, aunque nos parezca inmerecido o extraño. También indica que no queremos intervenir en los asuntos de otros, dejando la responsabilidad en manos de una autoridad superior.", origen: "Tiene un trasfondo religioso y jerárquico. En la tradición católica, San Pedro es el custodio de las llaves del cielo y representante de la Iglesia; por tanto, si Dios otorga una gracia, San Pedro (la autoridad terrenal) solo puede ratificarla y bendecirla sin cuestionarla." },
    { urlImagen: "Imagesdichos/cesto_cientos.webp", expresion: "«Quien hace un cesto hace ciento»", significado: "Indica que quien comete una falta o tiene un comportamiento determinado una vez, es muy probable que lo repita. Se usa para advertir que las acciones definen un hábito o el carácter de una persona.", origen: "Proviene del mundo de la artesanía y la cestería. Se basa en la idea de que una vez que se ha aprendido la técnica para fabricar el primer cesto (o se ha perdido el miedo a cometer un error), el resto vendrán rodados por inercia o costumbre." },
    { urlImagen: "Imagesdichos/col_lechuga.webp", expresion: "«Entre col y col, lechuga»", significado: "Indica que en medio de una tarea monótona o una serie de cosas iguales, conviene introducir algo diferente para variar y hacerlo más ameno. Se usa para justificar una distracción o un cambio de tema en una conversación larga.", origen: "Proviene de la agricultura tradicional. Los hortelanos solían plantar lechugas entre las hileras de coles para aprovechar mejor el terreno y el tiempo de riego, ya que la lechuga crece mucho más rápido. Así, la 'lechuga' rompía la monotonía del cultivo principal." },
    { urlImagen: "Imagesdichos/caer_burro.webp", expresion: "«Poner a alguien a bajar (caer) de un burro»", significado: "Criticar a alguien con dureza o reprenderlo severamente. Se usa cuando se enumeran todos los fallos de una persona sin filtros.", origen: "Proviene de la expresión 'caer del burro' (reconocer un error). Al 'poner a alguien a caer del burro', lo que hacemos es forzarlo —mediante la crítica— a que reconozca sus faltas o baje de su pedestal de terquedad." },
    { urlImagen: "Imagesdichos/boca_cerrada.webp", expresion: "«En boca cerrada no entran moscas»", significado: "Es una advertencia sobre la prudencia. Nos recuerda que es mejor callar y ser discretos que hablar de más y cometer un error o causar un problema innecesario.", origen: "Aunque es de tradición oral, se tiene constancia de su uso desde el siglo XIV en textos arábico-andaluces. La metáfora es sencilla: quien mantiene la boca cerrada se ahorra tragar algo desagradable (o decir algo inconveniente)." },
    { urlImagen: "Imagesdichos/febrero_humero.webp", expresion: "«'En febrero un rato al sol y otro al humero' y 'En febrero saca la lengua el perro'.»", significado: "Ambos reflejan la inestabilidad de febrero. El primero alude a que el tiempo cambia tanto que pasas de buscar el sol a refugiarte en el humero (la chimenea). El segundo indica que ya empiezan a darse días de calor impropio que hacen que el perro jadee.", origen: "Son refranes del mundo rural y pastoril. Febrero es un mes de transición; el 'humero' era el lugar de la casa donde se ahumaba la matanza y se buscaba el calor del fuego, mientras que el 'perro con la lengua fuera' simboliza los primeros amagos de primavera que engañan a la naturaleza." },
    { urlImagen: "Imagesdichos/dios_rogando.webp", expresion: "«A Dios rogando y con el mazo dando»", significado: "Enseña que no basta con rezar o esperar ayuda externa; es necesario esforzarse y trabajar por lo que se desea. La ayuda divina debe ir acompañada de la acción personal.", origen: "Citado por Cervantes en El Quijote, se atribuye a un encuentro entre San Bernardo y un carretero cuyo carro se rompió. Al pedir el hombre un milagro, el santo le respondió: “Yo rogaré a Dios, amigo, y tú entretanto da con el mazo (trabaja en arreglarlo)”." },
    { urlImagen: "Imagesdichos/digo_diego.webp", expresion: "«Donde dije digo, digo Diego»", significado: "Se utiliza para rectificar una afirmación anterior o desdecirse de lo dicho. Es la fórmula perfecta para cuando alguien cambia de opinión o intenta corregir un error negando su declaración previa.", origen: "Proviene de un antiguo juego de palabras popular. Se basa en la similitud fonética entre 'digo' (del verbo decir) y el nombre propio 'Diego'. La frase completa, 'Donde dije digo, digo Diego', juega con ese sonido para transformar una palabra en otra y así anular lo dicho anteriormente con un toque de ingenio." },
    { urlImagen: "Imagesdichos/tirar_la_toalla.webp", expresion: "«Tirar la toalla»", significado: "Significa rendirse ante una dificultad, desistir de un empeño o reconocer que no se puede ganar una batalla. Es admitir la derrota y abandonar el esfuerzo que se estaba realizando.", origen: "Proviene del mundo del boxeo. Cuando un entrenador ve que su boxeador está recibiendo demasiado castigo y no puede continuar, arroja una toalla al centro del ring. Es la señal reglamentaria para que el árbitro detenga el combate de inmediato." },
    { urlImagen: "Imagesdichos/madrugar.webp", expresion: "«No por mucho madrugar amanece más temprano»", significado: "Advierte que no por precipitarse o actuar con excesiva premura se logran antes los resultados. Nos recuerda la importancia de la paciencia y de 'darle tiempo al tiempo', ya que hay procesos naturales que no se pueden acelerar.", origen: "Es un refrán de tipo meteorológico y agrícola. Se basa en la observación de la naturaleza: el ciclo del sol es inalterable y no depende del esfuerzo humano. Surgió en el entorno rural para enseñar que el éxito requiere no solo trabajo (madrugar), sino también respetar los tiempos adecuados." },
    { urlImagen: "Imagesdichos/ciego.webp", expresion: "«No hay peor ciego que el que no quiere ver»", significado: "Se refiere a las personas que, teniendo la verdad o la evidencia delante, se niegan a aceptarla por prejuicio o conveniencia. Indica que es imposible convencer a alguien que ha decidido cerrar su mente.", origen: "Tiene una base bíblica y filosófica muy antigua, presente en diversas culturas. La frase subraya que la ceguera física es una limitación natural, pero la ceguera mental es una elección voluntaria, lo que la hace mucho más difícil de 'curar'." },
    { urlImagen: "Imagesdichos/trapo.webp", expresion: "«Poner a alguien como un trapo»", significado: "Significa reprender a alguien con mucha dureza, insultarlo o criticarlo de forma despiadada, dejándolo sin capacidad de defensa o moralmente 'por los suelos'.", origen: "La metáfora alude al uso de los trapos de limpieza, que se estrujan, se ensucian y se tiran con desprecio tras ser usados. Al tratar a una persona como un trapo, se le quita su dignidad, manejándola y despreciándola como si fuera un objeto viejo y sin valor." },
    { urlImagen: "Imagesdichos/pajaro_en_mano.webp", expresion: "«Más vale pájaro en mano que ciento volando»", significado: "Aconseja valorar lo que se tiene de forma segura, aunque sea poco, en lugar de ambicionar cosas mejores que son inciertas o difíciles de conseguir. Es un elogio a la seguridad frente al riesgo.", origen: "Proviene de la antigua cetrería y el arte de la caza. Para un cazador, tener una presa ya capturada 'en la mano' era una garantía de alimento, mientras que ver muchas aves en el aire no servía de nada si no lograba atrapar ninguna." },
    { urlImagen: "Imagesdichos/mal_tiempo_buena_cara.webp", expresion: "«Al mal tiempo, buena cara»", significado: "Aconseja mantener una actitud positiva y optimista cuando las cosas van mal o surgen contratiempos. Nos recuerda que, aunque no podamos cambiar las circunstancias, sí podemos elegir cómo reaccionar ante ellas.", origen: "Proviene de la sabiduría popular marinera y agrícola. Antiguamente, cuando el clima impedía faenar o trabajar el campo, el trabajador no ganaba nada lamentándose; por ello, se recomendaba mantener el ánimo alto para estar listos y con fuerzas en cuanto el temporal amainara." },
    { urlImagen: "Imagesdichos/perro_ladrador.webp", expresion: "«Perro ladrador, poco mordedor.»", significado: "Se aplica a personas que amenazan mucho, hablan con arrogancia o hacen mucho ruido, pero que a la hora de actuar no hacen nada. Sugiere que quien mucho presume, poco suele cumplir.", origen: "Proviene de la observación del comportamiento animal. En el mundo canino, un perro que ladra constantemente lo hace por miedo o para marcar territorio desde lejos, mientras que el perro que realmente va a atacar suele estar callado y tenso antes de morder." }
  ]
  const refranesDatos = [
    { urlImagen: "Imagesdichos/clavo_saca_clavo.png", expresion: "«Un clavo saca otro clavo»", significado: "Significado: Indica que un nuevo afecto o preocupación ayuda a olvidar y superar una pena anterior del mismo tipo. Se aplica sobre todo en el amor, bajo la creencia de que un nuevo enamoramiento cura el dolor de un desengaño previo.", origen: "Origen: Es un dicho de gran antigüedad basado en la carpintería. Alude a la técnica técnica de usar un clavo nuevo para empujar y extraer uno que ha quedado atascado en la madera. Metafóricamente, el 'clavo nuevo' ocupa el lugar del antiguo, desplazando el dolor." },
    { urlImagen: "Imagesdichos/boca_verdades.png", expresion: "«Boca de verdades, cien enemistades»", significado: "Significado: Advierte que decir siempre la verdad de forma cruda y sin filtros suele generar rechazo y crearse enemigos. Aunque la sinceridad es una virtud, este refrán señala que a mucha gente le incomoda escuchar verdades incómodas sobre sí misma.", origen: "Origen: Es un dicho de carácter moral y social muy antiguo. Se basa en la observación de la convivencia humana: la verdad suele ser 'amarga', y quien la practica de manera implacable termina alejando a los demás, prefiriendo la sociedad, a menudo, una mentira cortés o el silencio." },
    { urlImagen: "Imagesdichos/camaron_corriente.png", expresion: "«Camarón que se duerme se lo lleva la corriente»", significado: "Significado: Advierte sobre las consecuencias de la pereza o la falta de atención. Indica que si alguien se descuida, se confía o no aprovecha las oportunidades en el momento preciso, acabará perdiéndolas o sufriendo consecuencias negativas por su inacción.", origen: "Origen: Proviene de la observación de la vida en los ríos y costas. Los camarones suelen sujetarse a las rocas o al fondo para alimentarse; si se quedan dormidos o se relajan, pierden su agarre y la fuerza del agua los arrastra inevitablemente hacia el mar o hacia depredadores." },
    { urlImagen: "Imagesdichos/a_otro_perro.png", expresion: "«A otro perro con ese hueso»", significado: "Significado: Se utiliza para rechazar un engaño, una mentira o una excusa poco creíble. Es una forma de decirle a alguien que no somos tan ingenuos como para creer lo que nos está contando y que intente convencer a otra persona más incauta.", origen: "Origen: La metáfora es muy sencilla: un hueso sin carne es un regalo pobre y sin valor. Si intentas dárselo a un perro que ya sabe que no hay nada que comer ahí, lo rechazará. El dicho traslada esta idea a las palabras: 'no intentes darme este engaño a mí, que ya te he calado'." },
    { urlImagen: "Imagesdichos/no_corre_vuela.png", expresion: "«El que no corre, vuela»", significado: "Significado: Se refiere a que, en un entorno competitivo, todos están atentos para sacar provecho de las oportunidades. Indica que no hay nadie descuidado y que, si alguien parece ir despacio ('correr'), en realidad hay otros que van aún más rápido ('vuelan') para adelantarse.", origen: "Origen: Es una evolución de la observación del movimiento. Si correr ya implica rapidez, volar representa el grado máximo de velocidad y astucia. El dicho nació para describir la viveza de la gente en situaciones donde los recursos son escasos y solo el más rápido obtiene el beneficio." },
    { urlImagen: "Imagesdichos/mentiroso_cojo.png", expresion: "«Se coge antes a un mentiroso que a un cojo»", significado: "Significado: Indica que la mentira tiene patas muy cortas. Tarde o temprano, el mentiroso cae en contradicciones o se descubre la verdad, por lo que su 'captura' o exposición es incluso más rápida que la de alguien que tiene dificultades para caminar.", origen: "Origen: Es una comparación exagerada basada en la observación física. Mientras que un cojo tiene una limitación real para avanzar, el mentiroso se ve frenado por su propia falta de memoria o por la lógica de los hechos. La frase subraya que la verdad siempre termina alcanzando al engaño." },
    { urlImagen: "Imagesdichos/genio_figura.png", expresion: "«Genio y figura hasta la sepultura»", significado: "Significado: Indica que el carácter, la personalidad y los rasgos distintivos de una persona no cambian con el tiempo. Sugiere que nacemos con una forma de ser que nos acompaña, para bien o para mal, durante toda la vida hasta la muerte.", origen: "Origen: Proviene de la literatura clásica española. En este contexto, 'genio' no se refiere a la inteligencia, sino al temperamento natural, y 'figura' alude al aspecto o comportamiento exterior. La rima con 'sepultura' enfatiza que la esencia humana es inmutable y permanente." },
    { urlImagen: "Imagesdichos/zapatero_zapatos.png", expresion: "«Zapatero a tus zapatos»", significado: "Significado: Aconseja que cada persona debe limitarse a opinar o trabajar en aquello que realmente conoce y en lo que tiene experiencia, evitando meterse en asuntos o profesiones que no le competen o de los que carece de conocimientos.", origen: "Origen: Se atribuye al pintor griego Apeles (siglo IV a.C.). Se dice que un zapatero criticó la forma de una sandalia en uno de sus cuadros y el pintor la corrigió. Pero, al ver que el hombre empezaba a criticar otras partes de la obra, Apeles le respondió: 'Ne sutor ultra crepidam' (El zapatero no debe ir más allá de la sandalia)." },
    { urlImagen: "Imagesdichos/mal_muchs_consuelo_tontos.png", expresion: "«Mal de muchos, consuelo de tontos»", significado: "Significado: Critica la actitud de quienes se sienten aliviados al ver que su propia desgracia también afecta a otros. Sugiere que el hecho de que un problema sea común no lo hace menos grave, y buscar consuelo en el infortunio ajeno es propio de personas poco inteligentes o conformistas.", origen: "Origen: Es un refrán de tradición popular que busca combatir la resignación. Históricamente, se utilizaba para motivar a las personas a buscar soluciones individuales en lugar de aceptar la derrota simplemente porque 'a todo el mundo le pasa lo mismo', especialmente en épocas de pestes o malas cosechas." },
    { urlImagen: "Imagesdichos/perro_hortelano.png", expresion: "«Ser como el perro del hortelano»", significado: "Significado: Se refiere a las personas que no disfrutan de algo ni permiten que los demás lo hagan. Describe esa actitud envidiosa o egoísta de quien, al no poder o no querer aprovechar una oportunidad, impide que otros la aprovechen.", origen: "Origen: Proviene de una antigua fábula. El perro del hortelano (el que cuida el huerto) no come las verduras porque es carnívoro, pero tampoco deja que los bueyes u otros animales se acerquen a comerlas, ladrándoles para alejarlos. Su comportamiento es absurdo: vigila algo que a él no le sirve de nada." },
    { urlImagen: "Imagesdichos/mangas_verdes.png", expresion: "«A buenas horas, mangas verdes»", significado: "Significado: Se utiliza para criticar que algo llega o sucede cuando ya es demasiado tarde, cuando el problema ya se ha resuelto por sí solo o cuando ya no tiene remedio ni utilidad.", origen: "Origen: Proviene de la Santa Hermandad (un cuerpo de seguridad creado por los Reyes Católicos). Sus miembros vestían un uniforme con mangas verdes. Tenían fama de ser muy lentos y llegar a los pueblos cuando los delitos ya se habían cometido y los malhechores habían escapado; por ello, los vecinos les recibían con esta frase irónica." },
    { urlImagen: "Imagesdichos/caballo_diente.png", expresion: "«A caballo regalado, no le mires el diente»", significado: "Significado: Recomienda aceptar los regalos o favores con gratitud, sin criticarlos ni buscarles defectos o faltas. Sugiere que, al no haber costado dinero ni esfuerzo, no es cortés evaluar minuciosamente su calidad o valor.", origen: "Origen: Proviene de la antigua costumbre de revisar la dentadura de los caballos para determinar su edad y estado de salud. Un comprador siempre miraba los dientes para saber si el animal era viejo; sin embargo, si el caballo era un regalo, hacer esa inspección se consideraba un gesto de mala educación y desprecio hacia el donante." },
    { urlImagen: "Imagesdichos/cerdo_san_martin.png", expresion: "«A cada cerdo le llega su San Martín»", significado: "cometido injusticias le llega su castigo o el momento de rendir cuentas. Es un recordatorio de que nadie escapa de las consecuencias de sus actos.", origen: "Origen: Proviene de la tradición rural española de realizar la matanza del cerdo coincidiendo con la festividad de San Martín de Tours (11 de noviembre). El refrán utiliza esta fecha inevitable para el animal como una metáfora de que el tiempo de impunidad siempre tiene un final." },
    { urlImagen: "Imagesdichos/falta_pan.png", expresion: "«A falta de pan, buenas son tortas»", significado: "Significado: Recomienda conformarse con lo que se tiene cuando no se puede conseguir algo mejor. Invita a la flexibilidad y al pragmatismo: si no tienes exactamente lo que deseas, debes valorar y aprovechar la alternativa disponible que sea útil.", origen: "Origen: Históricamente, las 'tortas' eran panes planos, sin levadura y de menor calidad que el pan blanco de panadería. Cuando en una casa se acababa el pan principal, se recurría a estas tortas más sencillas. La frase nació para indicar que lo importante es cubrir la necesidad básica, aunque no sea con el producto ideal." },
    { urlImagen: "Imagesdichos/mona_seda.png", expresion: "«Aunque la mona se vista de seda, mona se queda»", significado: "Significado: Indica que, por mucho que alguien intente ocultar sus defectos o cambiar su apariencia externa con ropa cara o lujos, su verdadera naturaleza, esencia o falta de educación siguen siendo evidentes. Lo exterior no cambia la realidad del interior.", origen: "Origen: Es un dicho muy antiguo popularizado por el fabulista Tomás de Iriarte. La metáfora es visual y cómica: vestir a un primate con telas nobles (seda) no le quita su condición de animal. Subraya la idea de que la elegancia o la clase no se pueden comprar si no se tienen de verdad." },
    { urlImagen: "Imagesdichos/marta_harta.png", expresion: "«Bien canta Marta después de harta»", significado: "Significado: Indica que es mucho más fácil estar alegre, ser amable o trabajar con ganas cuando las necesidades básicas (como el hambre o la seguridad) están cubiertas. Critica o señala que el buen humor a veces depende más de la comodidad que de la virtud.", origen: "Origen: Es un refrán de la sabiduría popular española que juega con la rima. La figura de 'Marta' representa a cualquier persona común. Antiguamente, se usaba para notar que los trabajadores o los invitados no mostraban su mejor cara ni su talento hasta que no habían comido y bebido en abundancia." },
    { urlImagen: "Imagesdichos/yo_caliente.png", expresion: "«Ande yo caliente, ríase la gente»", significado: "Significado: Expresa que lo más importante es el bienestar personal o la propia satisfacción, sin que importen las críticas, las burlas o las opiniones ajenas. Defiende la idea de actuar según la propia conveniencia aunque parezca ridículo ante los demás.", origen: "Origen: Fue popularizado por el famoso escritor del Siglo de Oro Luis de Góngora en una de sus letrillas satíricas. La metáfora se refiere a preferir ir bien abrigado (caliente) en invierno, aunque la ropa sea fea o pasada de moda, antes que ir elegante pasando frío solo por el qué dirán." },
    { urlImagen: "Imagesdichos/ojo_diente.png", expresion: "«Ojo por ojo, diente por diente»", significado: "Significado: Se refiere al principio de reciprocidad en la justicia, donde el castigo debe ser igual al daño causado. Se usa para justificar la venganza o para advertir que cualquier agresión recibirá una respuesta idéntica.", origen: "Origen: Es una de las normas más antiguas de la humanidad, conocida como la Ley del Talión. Aparece en el Código de Hammurabi y en textos bíblicos. En su época, aunque parezca cruel, fue un avance social, ya que limitaba la venganza para que no fuera excesiva, obligando a que el castigo fuera proporcional a la falta." },
    { urlImagen: "Imagesdichos/bien_juega.png", expresion: "«Bien juega quien mira»", significado: "Significado: Sugiere que la persona que observa una situación desde fuera, sin estar involucrada emocionalmente o bajo presión, tiene una visión más clara y objetiva de lo que está sucediendo. Es un consejo sobre la importancia de la observación y la prudencia antes de actuar.", origen: "Origen: Proviene del mundo de los juegos de azar y de mesa (como el ajedrez o las cartas). Se observaba que los espectadores solían detectar los errores de los jugadores y las mejores jugadas posibles con más facilidad que los propios participantes, quienes, al estar nerviosos o arriesgando su dinero, perdían la perspectiva del juego." },
    { urlImagen: "Imagesdichos/presumes_careces.png", expresion: "«Dime de qué presumes y te diré de qué careces»", significado: "Significado: Sugiere que las personas suelen alardear de virtudes, méritos o posesiones que en realidad no tienen, con el fin de ocultar sus propias inseguridades o carencias. La ostentación es, a menudo, una máscara para tapar un vacío.", origen: "Origen: Es un refrán de base psicológica popular. Se fundamenta en la observación de la conducta humana: quien tiene algo de forma natural y segura no siente la necesidad de proclamarlo constantemente. La sabiduría popular detectó que el exceso de presunción suele ser un mecanismo de defensa para proyectar una imagen que no corresponde con la realidad." }
  ]
  return (
    /* Container */
    <div className="w-full h-screen flex flex-col bg-[#0f0e0b]">
      <header className="w-full col-span-1 p-10 flex flex-col gap-6 self-start xl:col-span-1 xl:flex-row xl:justify-between xl:items-center">
        <div className="flex flex-row justify-between items-center">
          {/* Logo */}
          <div className="flex flex-row justify-start items-center gap-2.5">
            <div className="bg-yellow-500 w-10 h-10"></div>
            <h1 className="font-bold text-white text-2xl">Hispanialengua</h1>
          </div>
          {/* Boton menu */}
          <button className="lg:hidden w-10 h-10" onClick={() => { setMenuDesplegable(!menuDesplegable) }}>
            <svg width="800px" height="800px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#ffffff">

              <g id="SVGRepo_bgCarrier" stroke-width="0" />

              <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" />

              <g id="SVGRepo_iconCarrier"> <path d="M4 6H20M4 12H20M4 18H20" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" /> </g>

            </svg>
          </button>
        </div>
        {/* Menu */}
        <ul className={`text-white ml-[20%] lg:flex lg:flex-row lg:ml-0 justify-center items-start gap-8 ${menuDesplegable ? "flex flex-col justify-center items-start gap-8" : "hidden"}`}>
          <li><Link to={"/capsulas"}>Cápsulas</Link></li>
          <li><Link to={"/paremias"}>Paremias</Link></li>
          <li><Link to={"/espanol-vivo"}>Español vivo</Link></li>
          <li><Link to={"/juegos"}>Juegos</Link></li>
          <li className="text-yellow-500"><Link to={"/trabalenguas"}>Trabalenguas</Link></li>
          <li><Link to={"/cortos"}>Cortos</Link></li>
          <li><Link to={"/cultura"}>Cultura</Link></li>
          <li><Link to={"/musica"}>Música</Link></li>
          <li><Link to={"/comarca"}>Comarca</Link></li>
          <li><Link to={"/sobre-nosotros"}>Sobre nosotros</Link></li>
          <li><Link to={"/"}>Home</Link></li>
        </ul>
      </header>
      <main className="w-full flex-1 flex flex-col">
        {/* Botones */}
        <div className="w-fit mx-auto bg-white/80 flex flex-row justify-center items-center text-2xl drop-shadow-[0_2px_4px_rgba(0,0,0,0.8)] rounded-lg backdrop-blur-sm font-bold mb-8">
          <button className={`text-[#0f0e0b] px-3 py-1 rounded-tl-lg rounded-bl-lg ${dichos ? "bg-amber-500" : ""}`} onClick={() => {
            setDichos(true)
            setRefranes(false)
          }}>Dichos</button>
          <button className={`text-[#0f0e0b] px-3 py-1 rounded-tr-lg rounded-br-lg ${refranes ? "bg-yellow-500" : ""}`} onClick={() => {
            setRefranes(true)
            setDichos(false)
          }}>Refranes</button>
        </div>
        {/* Container paremias */}
        <div className="flex flex-col flex-1">
          {/* Dichos */}
          <article className={`w-full flex-1 flex flex-col text-2xl text-white ${dichos ? "block" : "hidden"}`}><ParemiasComp paremias={dichosDatos} titulo="Dichos" /></article>
          {/* Refranes */}
          <article className={`w-full flex-1 text-2xl text-white ${refranes ? "block" : "hidden"}`}><ParemiasComp paremias={refranesDatos} titulo="Refranes" /></article>
        </div>
      </main>
    </div>
  )
}

export default Paremias